DensityCo/dashboard

- src/components/visualization-space-detail-raw-events-card/index.js
> chore: ensure that raw events are sorted with newest events first

- package-lock.json
- package.json
- src/components/insights-space-detail-utilization-card/index.js
- src/components/visualization-space-detail-24-hour-chart/index.js
- src/components/visualization-space-detail-daily-metrics-card/_styles.scss
- src/components/visualization-space-detail-daily-metrics-card/index.js
Integrates https://github.com/DensityCo/charts/pull/29
DEN-4417
> Line chart integration into dashboard

- package-lock.json
- package.json
> Add updated conduit version with debounce

- package.json
Bumps UI to include a fix to the positioning of cards to support loaders.
> Finalize card style fixes

- src/components/insights-space-detail-utilization-card/index.js
- src/components/visualization-space-detail-daily-metrics-card/index.js
- Fix hardcoded timezone in utilization chart
- Adjust the utilization timestamp aggregation to make it less confusing
ISGT-60
> Utilization chart timescale

- src/components/insights-space-detail-utilization-card/index.js
> Timezone offset in space average utilization

- src/components/live-space-card/_styles.scss
- src/components/live-space-card/index.js
- Adds ellipsis to live space card, which more gracefully handles long space names.
> Live card overflow ellipsis

- src/client/index.js
- src/components/login/index.js
- src/index.js
- src/reducers/user/index.js
- src/reducers/user/test.js
- When an api request returns a 403, redirect the user to the login page.
- Add `userError` action on user collection.
> Login semantics

- src/components/account-setup-doorway-detail/index.js
> Update language in account setup doorway detail page

- src/components/insights-space-detail-foot-traffic-card/index.js
This was an issue because it turns out that if data is requested for a time period that doesn't subdivide into even intervals, then more data than expected will be returned. Therefore, the chart should filter the data prior to rendering it to only display data that fits within its bounds. Furthermore, if removing a final section of data would leave a gap, fill in that gap by adding a final point at the end of the chart on days that aren't the current day (the current day hasn't finished yet!)
Old behavior:
New behavior:
> Only draw data that fits within the foot traffic chart

- src/components/insights-space-detail-raw-events-export-card/_styles.scss
- src/components/insights-space-detail-raw-events-export-card/index.js
The type of startDate and endDate are no longer moments
> Accidentally broke csv export

- src/components/dashboard/_styles.scss
Now with 100% less >100% width rendering!
> Dashboard header layout fix

- src/store.js
A redux dev tools breaking change that is coming down the pipeline. Currently, both are supported to allow people to migrate.
> Rename redux dev tools extension

- package-lock.json
- package.json
- src/client/index.ts
- src/client/specs/core-api.json
- src/components/environment-switcher/_styles.scss
- src/components/environment-switcher/index.tsx
- src/index.tsx
This change un-reverts https://github.com/DensityCo/dashboard/pull/125 and adjusts two lines to not include the query string parameter when the box is not checked.
DEN-7221
> Go fast change

- src/actions/route-transition/explore-space-trends.ts
- src/components/explore-space-detail-hourly-breakdown-card/index.tsx
- src/components/explore-space-trends/index.tsx
- src/helpers/generate-hourly-breakdown-ephemeral-report/index.ts
Made the peaks chart to averages
> Moved peak report to average

- src/components/explore-space-detail-raw-events-export-card/index.tsx
Downloads get sent to Mixpanel
> Tracking data downloads

- package-lock.json
- src/actions/route-transition/explore-space-trends.ts
- src/reducers/spaces/index.ts
Let me know if I need to clean up the `explore-space-trends.ts` page logic. But, essentially, this means that once you select a date range, you maintain that date range.
Apparently, this was driving customers nuts, since the date range would reset every time they clicked on a space.
> Maintain the date range when jumping between spaces

- package-lock.json
- package.json
- src/styles.scss
And a few other things, like change the border color of inputs. Contains https://github.com/DensityCo/ui/pull/93 and https://github.com/DensityCo/ui/pull/94.
> Update font to aeonik

- package-lock.json
- src/components/explore/index.tsx
This changes the search field so that it uses the ancestry part of the space object to filter up the hierarchy. Gives you a better sense as to where you are when searching.
> Filter by ancestry

- package-lock.json
- src/actions/collection/users/create.ts
Tracking when user invites another user
> Added in mixpanel

- package-lock.json
- src/actions/route-transition/explore-space-trends.ts
- src/components/explore-space-header/index.tsx
- src/components/explore-space-trends/index.tsx
- src/helpers/multi-week-selection/index.ts
The hourly peak chart shouldn't say "Average" if its just for a week.
> Shouldn't say "Average" when it's less than a week

- src/actions/collection/digest-schedules/create.ts
I want to track how many people (and who!) create email digests
> Greedy for data

- package-lock.json
- src/components/admin-user-management/index.tsx
Works end to end using production API
> Hotfix: Expired invitation resend

- package-lock.json
- package.json
- src/components/admin-locations-breadcrumb/index.tsx
- src/components/admin-locations-building-detail/index.tsx
- src/components/admin-locations-building-detail/styles.module.scss
- src/components/admin-locations-campus-detail/index.tsx
- src/components/admin-locations-campus-detail/styles.module.scss
- src/components/admin-locations-floor-detail/README.md
- src/components/admin-locations-floor-detail/index.tsx
- src/components/admin-locations-floor-detail/styles.module.scss
- src/components/admin-locations-list-view-image/README.md
- src/components/admin-locations-list-view-image/index.tsx
- src/components/admin-locations-list-view-image/styles.module.scss
- src/components/admin-locations-root-detail/README.md
- src/components/admin-locations-root-detail/index.tsx
- src/components/admin-locations-root-detail/styles.module.scss
- src/components/admin-locations-subheader/README.md
- src/components/admin-locations-subheader/index.tsx
- src/components/admin-locations-subheader/styles.module.scss
- src/components/admin-locations/index.tsx
- src/components/admin-locations/styles.module.scss
- src/components/list-view/index.tsx
- src/components/list-view/styles.module.scss
- utilities/make-component
This pull request adds detail pages within the space management ui for campuses, buildings, and floors.
The styling is still a bit wonky though.
> Space management detail pages

- package-lock.json
- src/helpers/mixpanel-user-reducer-enhancer/index.ts
This checks localstorage to see if a user is currently in impersonation mode and then doesn't track them in mixpanel
> Only track non-impersonated users

- src/actions/route-transition/explore-space-trends.ts
https://densityio.atlassian.net/browse/DEN-7848
> Dont break on space start

- package-lock.json
- package.json
https://github.com/DensityCo/reports/pull/26
Bumped reports version to handle some edge-cases re: zero-bookings and long email names
> bump report version to 4.5.2

- src/helpers/date-range-picker-is-outside-range/index.js
> Add hacky fix to try to work around more date picker problems

- package-lock.json
- src/actions/user/update.ts
- src/components/account-registration/README.md
- src/components/account-registration/index.tsx
- src/components/account-setup-overview/index.tsx
- src/components/account/index.tsx
- src/types.ts
Removed all traces of `nickname` from user-based views. Resolves [DEN-7914](https://densityio.atlassian.net/browse/DEN-7914).
Tested all views + forms locally. Will need to also modify core-api to utilize the full name field in emails instead of nickname.
> Remove nickname

- package-lock.json
- src/helpers/date-range-picker-is-outside-range/index.js
Now that we've got the reports db in place, we can bump up the max number of days that a space can generate analytics for.
> Space date picker max range to 6 months

- src/components/dashboard/index.tsx
- src/components/explore/index.tsx
- Made both pages class based. 
- Wrapped them in a div with a ref (since you cant ref a functional component)
- Attached window listeners to change `onResize`
- Change width of sidebar
> Resizing based on ref and window listeners

- src/components/admin-developer/index.tsx
- src/components/admin-token-create-modal/index.tsx
- src/components/admin-token-update-modal/index.tsx
- src/components/admin-webhook-create-modal/index.tsx
- src/components/admin-webhook-update-modal/index.tsx
> code: stateless modals for token/webhook management

- src/components/admin-locations-detail-modules/general-info.tsx
- src/components/admin-locations-detail-modules/index.tsx
- src/components/admin-locations-detail-modules/metadata.tsx
Adds an abstraction to minimize the amount of duplicated code we have in the metadata and general info modules.
> Space field renderer

- src/components/intercom/index.tsx
We will be syncing org ID across Intercom, Mixpanel, and Salesforce. This pushes org ID and name to intercom fields.
> Added in org ID and name to intercom data

- src/components/admin-locations-detail-modules/general-info.tsx
Adds space functions, to keep in line with Core API. This should be released after https://github.com/DensityCo/core-api/pull/960.
> Additional space functions

- src/fields.ts
updates the naming scheme for core on dev clusters
> update core api naming scheme for dev clusters

- src/components/explore-alert-management-modal/index.tsx
- src/components/explore-alert-management-modal/styles.module.scss
- src/components/explore/index.tsx
@guscost I'm looking to simplify this alert a bit. I'd like for the default to be "one-time." I changed the verbiage as well to make it clear that the third field is about how many times we'll notify the user.
Completes: https://densityio.atlassian.net/browse/DEN-8436
I'm having trouble making “Notify me at most” perform the following logic:
- Selecting "Once" changes it to one-time + null cooldown.
- Selecting anything else changes it to "one-time: false" and adds the cooldown.
The other issue I'd like to tackle here:
- https://densityio.atlassian.net/browse/DEN-8444
> Updating alert verbiage

- package-lock.json
- package.json
Periodic Metrics, Occupancy Distribution, and Time Occupied
> Update density reports to add three new reports

- package-lock.json
- src/components/admin-device-status/index.tsx
- src/components/admin-device-status/styles.module.scss
Added in WiFi and LAN status to the DPU status page
> Dpu Status

- package.json
> reports bump

- package-lock.json
- src/components/analytics-control-bar-interval-filter/index.tsx
- src/components/analytics-control-bar-interval-filter/story.tsx
- src/components/analytics-control-bar/index.tsx
- src/components/analytics-control-bar/story.tsx
- src/components/analytics-table/index.tsx
- src/components/analytics-table/story.tsx
- src/types/analytics.ts
- renamed `AnalyticsInterval` to `QueryInterval`
- renamed properties of `Query` to better match types/names being used elsewhere:
- `timeframe` => `dateRange`
- `granularity` => `interval`
`Resource`-related typings are currently stuck in `types/analytics.ts`, not sure if they should be separated.
> Analytics types

- src/helpers/space-function-choices/index.ts
> bug(space-function-choices): look up space functions correctly in the

- package-lock.json
- src/components/analytics-tabs/README.md
- src/components/analytics-tabs/index.tsx
- src/components/analytics-tabs/story.tsx
- src/components/analytics-tabs/styles.module.scss
- src/types/analytics.ts
Adds a tab bar which will be used to display a list of analytics queries that are open.
> Analytics tabs

- src/fields.ts
Adds the dr region urls to dashboard so that we can vet the system.
> add dr region to dashboard

- src/helpers/space-function-choices/index.ts
- src/types/index.ts
Don't deploy until https://github.com/DensityCo/core-api/pull/1139 is live
> Space function: retail

- src/components/intercom/index.tsx
Adds role & consent attributes to intercom user definition, for use in segmenting
> DEN-9193: Intercom user metadata

- package-lock.json
- src/components/app-navbar/index.tsx
- src/components/app-navbar/styles.module.scss
Add a support link to the navbar that opens in a new tabs so that customers know our support center actually exists.
> PRD-103 / Adds support link to navbar

- package-lock.json
- src/components/space-picker/index.tsx
I'm adding a class to each space list item that contains information about it's space type. I'd also like to add one containing information about it's space function. I could use some quick help on where to find that.
Additionally, I prefer this be an html data attribute or something, but a class works just fine.
> added space type class to each space list element

- package-lock.json
- src/components/admin-locations/styles.module.scss
- src/components/spaces-live-events/index.tsx
- src/components/spaces-live-events/styles.module.scss
- src/components/spaces-snippets/index.tsx
- src/components/spaces/index.tsx
- src/components/spaces/styles.module.scss
**Spaces:**
**Location Management:**
> PRD-160/Spaces doorways nitpicks

- src/components/analytics/index.tsx
- src/helpers/analytics-datapoint/index.ts
- src/helpers/analytics-report/index.ts
- src/rx-stores/analytics/effects.ts
- src/rx-stores/analytics/index.ts
- src/rx-stores/analytics/reducer.test.ts
- src/rx-stores/analytics/reducer.ts
- src/rx-stores/space-hierarchy/index.ts
This PR does not alter any logic in the analytics store, but the pieces have been moved, renamed, and organized.
> Analytics store: organizational updates

- src/components/app-navbar/index.tsx
- src/rx-actions/queue/index.ts
- src/rx-stores/queue/index.ts
Reverts DensityCo/dashboard#900
> Revert "Migrate navbar to point to prototype"
