src/components/insights-space-detail-utilization-card/index.js
Previously, the utilization chart's y axis would always be bounded from `0%` to `100%`. There's a problem with that though if the utilization peaks for a space above `100%`:
This PR adds logic to ensure that the largest point on the y axis should either be:
```
1. The largest point on the graph, if larger than 100. (+ 10% in spacing)
2. 100.
```
=> Ensure that utilization chart never overflows its bounds

package-lock.json, package.json, src/actions/user/reset-password.js, src/components/account/_styles.scss, src/components/account/index.js, src/components/account/test.js, src/helpers/websocket-event-pusher/index.js, src/reducers/user/index.js, src/reducers/user/test.js
Was doing some investigation into some of the websockets issues we've found, and discovered some issues with the accounts page.
This PR addresses a few bugs:
- Canceling form after clicking edit resets the form back to the initial state, and rejects the edits (previously this wasn't being done). Test added to cover this.
- Changing password was causing a websocket infinite loop
- Effectively, this caused the token in the websocket event pusher module to not be updated in a graceful fashion.
- Change password toast shows properly and is dismissable
- Required some Density UI updates to make that happen, which are here: https://github.com/DensityCo/ui/pull/18
- In addition, as part of DEN-4528, fixed up and wrote some tests to ensure that the account page was handling errors properly. …
=> Change account page behavior

src/components/insights-space-list/index.js, src/components/insights-space-list/test.js
- Previously, the insights list page was displaying the number of count buckets under `n visits`, not the number of ingresses. This isn't the correct metric in this case.
- Added test to assert behavior.
=> Visits count adjustment

src/components/login/_styles.scss
It looks like at some point a static width was removed from the login
page error toast container. Add it back in.
=> Fix error banner width on login page

src/helpers/websocket-event-pusher/index.js, src/helpers/websocket-event-pusher/test.js
If the connectionState isn't reset, then attempting to reconnect again
will disconnect the already disconnected connection before reconnection,
which isn't ideal.
=> Sockets reconnect Instability

package-lock.json, package.json, src/client/index.js, src/components/account/index.js, src/components/account/test.js, src/components/dev-token-update-modal/_styles.scss, src/components/dev-token-update-modal/index.js, src/components/dev-webhook-list/index.js, src/components/insights-space-detail-utilization-card/index.js, src/components/insights-space-list/index.js, src/components/nav-logged-in/index.js, src/reducers/user/index.js
- Adjusted error handler - was previously redirecting to the login page when any 403 happened, now redirects when a response of `{"detail":"Incorrect authentication credentials"}` is received. Without this, anytime the demo user does anything they aren't supposed to, they get redirected to the login page.
- Disable the onboarding navbar item when the logged in user is a demo user.
<br/>
- Remove the `Edit` and `Change Password` links on the account page when the logged in user is a demo user.
=> Dashboard changes to support demo account

src/components/insights-space-detail-foot-traffic-card/index.js
If a time segment group is requested, remove empty count buckets that
are returned in that query.
=> Filter out data prior to chart on foot traffic chart

src/components/dev-webhook-create/index.js
Ben sent me a screenshot of the webhooks modal, it had some debugging text it looks like was never removed.
=> Remove extra error message in webhooks modal

package-lock.json, src/components/live-space-detail/_styles.scss
This allows the top part to stay visible until the screen shrinks to 300px in height. This was a request from Pier when demonstrating the live screen to a customer with a smaller screen. It kept hiding the top part and he was confused why it wouldn't show. 
I'm comfortable with this look.
=> Updated Live Screen to be max-height 300px for small screens

src/client/index.js, src/client/specs/accounts-api.json, src/components/account-registration/_styles.scss, src/components/account-registration/index.js
Adds core and marketing consent collection to the invited user registration page. Submits those values to the registration API endpoint.
Closes DEN-6666
- Consent checkboxes added
'Core' consent, acknowledging that the user has access to and confirms reading the TOS, is now required to complete the registration. Marketing consent is optional.
=> DEN-6666-Collect-consent

src/actions/user/update.js, src/client/specs/accounts-api.json, src/components/account/_styles.scss, src/components/account/index.js, src/components/account/test.js
Allows the user to edit their marketing consent and gives the user a link to click to contact support should they want to deactivate their account (i.e. revoke core consent).
Also removes `email` field from data submitted to user edit API endpoint.
Also updates account tests to replace deprecated test `equal` and `notEqual` calls to `strictEqual` and `notStrictEqual` respectively (`equal` and `notEqual` were deprecated in node v9.9.0).
Closes DEN-6668
- Fields added to account edit page
=> DEN-6668 edit consent

README.md
- Add "run" for NPM run script in ```make-component``` doc
=> [Docs] Typo fix on make-component

src/actions/route-transition/explore-space-trends.ts, src/components/explore-space-data-export/index.tsx, src/components/explore-space-detail-daily-metrics-card/index.tsx, src/components/explore-space-meetings/index.tsx, src/components/explore-space-trends/index.tsx, src/helpers/date-range-picker-is-outside-range/index.js
- The hourly breakdown report was missing a day when a date range was
selected.
- Changed how the days are grayed out to make a bit more sense maybe
This needs some testing, I'm not sure if this actually solves the problem fully.
DEN-7895
=> (try to) fix two bugs in relation to the date picker

src/components/explore-space-meetings/index.tsx, src/helpers/date-range-picker-is-outside-range/index.js
There was a typo in the meetings date picker's invocation of `isOutsideRange` it looks like, oops
DEN-7906
=> Fix meetings date picker issue

src/components/admin-locations-building-detail/index.tsx, src/components/admin-locations-campus-detail/index.tsx, src/components/admin-locations-floor-detail/index.tsx, src/components/admin-locations-space-detail/index.tsx, src/components/admin-locations/index.tsx, src/components/app-navbar/index.tsx
Reorder navbar dropdown so "locations" is the first item.
In addition (just something I noticed while doing the above work), hide the edit button on the space management pages if the user doesn't have the `core_write` permission.
=> Navbar dropdown reordering

src/index.tsx
Mixpanel charges us based on MTU (monthly tracked users). Anonymous users are counted as individual users.
A lot of MTUs come from un-auth'd users hitting the dashboard. This only tracks pageviews for auth'd users.
=> Only track mixpanel if user is logged in

src/fields.ts
Adds dev cluster urls for dev01 and dev02 to the list of available backends for the dashboard.
=> add dev clusters to the dropdown menu for core api backends

src/fields.ts
Updated the core api options but not the account api options.  We need both to authenticate using oauth.
=> accounts and core must be on the same cluster. 

src/actions/dashboards/destroy.ts, src/components/dashboard-edit/index.tsx, src/reducers/dashboards/index.ts
Previously, it was not being deleted from the collection. Also, it turns
out that some logic after the dashboard was being deleted was depending
on the dashboard still existing in the reducer, so I reordered a few
things / sdjusted how a few things work to get around that.
=> When deleting a dashboard, also delete it from the collection

package-lock.json, package.json, src/components/dashboard-report-edit-modal/index.tsx
Adds a new option to the report creation modal time range selector for absolute date range. When picked, it shows a date range picker (with the new `SMALL_WIDTH` context) and a timezone box to ensure that the date range is localized to a single time zone (as reports with multiple spaces make this difficult).
To make the time zone box a bit better though, if the report is a single space report and you have a space selected when selecting "absolute date range", it will auto populate the time zone based on the single space that was selected.
=> Absolute date range when creating reports

src/components/explore-control-bar/index.tsx
I think when this was last refactored, the signature of `onChangeDateRange`
changed, and it wasn't updated in all the places it should have been.
=> Adjust function signature of `onChangeCommonRange` in common range date range picker callback

public/index.html
Adds a metatag for validation with insightappsec:
https://www.rapid7.com/products/insightappsec/
The tag includes a randomly generated token to identify the domain to be scanned (e.g., prove we own the domain and are scanning for legitimate purposes).
=> Add validation tag for insightappsec for scanning

src/components/spaces-report-controller/styles.module.scss, src/components/spaces/index.tsx, src/components/spaces/styles.module.scss, src/helpers/use-auto-width/index.ts
- Preserve the "tab" that the user is on when switching spaces
- Add a message and link to the integrations admin when viewing a meeting room with no space mapping
=> New spaces page tweaks

src/components/dashboard-report-edit-modal/index.tsx
No default value was being set for the INSIGHT_LIST report control type,
causing the prop being passed to the report component to be not an array which
caused problems.
=> Set default value for INSIGHT_LIST report control type

.circleci/config.yml, package.json, src/helpers/filter-hierarchy/index.test.js, src/helpers/unsafe-set-settings-flag/index.test.js
Used the jest built-in `expect(thing).toThrowError()` rather than nodejs built-in `assert.throws(thing)`
Tests should now be able to run from node v10 and v12
=> use expect.toThrowError to avoid node version dependency in tests

src/components/admin-integrations/index.tsx
We don't need `channels:read` permission and Stripe won't activate the bot until we remove it.
=> Update scope of slackbot

src/components/analytics-line-chart/index.tsx
Fixes a bug where duplicate (future, nonexistent) counts were being shown.
I memoized this based on the timestamp, but made it ceil to the nearest hour to avoid constant re-rendering. This change reduces that to the nearest minute, which is fine for performance purposes but is too small an interval to cause the bug to be noticed by a user.
=> fix: filter was allowing duplicate future counts to be shown

src/components/admin-device-status/index.tsx, src/components/admin-device-status/styles.module.scss
Adds visibility into DPUs that are in low power mode, and prompts for remedy when 1 or more fall into that category. 
@rjgrazioli I took at stab at the styling for the warning pane, feel free to let me know how 
I should improve it.
Coupled with DensityCo/dashboard#610 (but can be deployed in any order)
=> [imp-90] Low power mode support

package-lock.json, package.json, src/components/dashboard-report-edit-modal/index.tsx, src/components/spaces-reports/index.tsx
This updates the "hourly breakdown" and "periodic metrics" reports so they are compatible with time segments that go "overnight".
=> Two overnight reports for "spaces" page

src/components/admin-locations-edit/index.tsx, src/components/admin-locations-root-detail/index.tsx, src/components/live-space-list/index.tsx, src/helpers/space-time-utilities/index.ts, src/index.tsx, src/rx-actions/collection/spaces-legacy/count-change.ts, src/rx-actions/collection/spaces-legacy/create.ts, src/rx-actions/collection/spaces-legacy/delete.ts, src/rx-actions/collection/spaces-legacy/destroy.ts, src/rx-actions/collection/spaces-legacy/error.ts, src/rx-actions/collection/spaces-legacy/fetch-all.ts, src/rx-actions/collection/spaces-legacy/filter.ts, src/rx-actions/collection/spaces-legacy/push.ts, src/rx-actions/collection/spaces-legacy/reset-count.ts, src/rx-actions/collection/spaces-legacy/set-default-time-range.ts, src/rx-actions/collection/spaces-legacy/set-events.ts, src/rx-actions/collection/spaces-legacy/set.ts, src/rx-actions/collection/spaces-legacy/update.ts, src/rx-actions/route-transition/live-space-detail.ts, src/rx-actions/route-transition/live-space-list.ts, src/rx-stores/analytics/effects.ts, src/rx-stores/space-management/index.ts, src/rx-stores/spaces-legacy/index.test.ts, src/rx-stores/spaces-legacy/index.ts, src/types/redux.ts
- added types to former Any fields
- removed unused filter fields
- added types for all spaces-legacy actions
- ensured all these actions make it into GlobalAction 🎉 
This looks like a big changeset, but it's almost entirely type annotations. I made a couple callouts in the notes below.
=> SpacesLegacyStore and spaces-legacy action types
